analyzer_rules:
# - explicit_self
# - unused_declaration

only_rules:
# - extension_access_modifier
- given_when_then # custom_rule
# - indentation_width
# - missing_docs
# - multiline_arguments_brackets
# - no_magic_numbers
# - object_literal
# - prefixed_toplevel_constant
# - redundant_string_enum_value
# - required_deinit
# - return_value_from_void_function
# - sorted_enum_cases
# - vertical_whitespace_between_cases
# - vertical_whitespace_closing_braces
# - vertical_whitespace_opening_braces
