name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

jobs:
  swift:
    name: Swift
    runs-on: macos-13
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Download swiftlint binary
      run: swift package resolve
    - name: Lint
      run: |
        DIRECTORY_NAME=$(echo "${PWD##*/}" | tr '[:upper:]' '[:lower:]')
        "$(find ".build/artifacts/${DIRECTORY_NAME}" -type f -name swiftlint -perm +111 -print -quit)" \
        lint --strict --reporter github-actions-logging
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
