name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app/Contents/Developer

jobs:
  swift:
    name: Swift
    runs-on: macos-13
    env:
      SIMULATOR: iPhone 14
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Download swiftlint binary
      run: swift package resolve
    - name: Lint
      run: |
        DIRECTORY_NAME=$(echo "${PWD##*/}" | tr '[:upper:]' '[:lower:]')
        "$(find ".build/artifacts/${DIRECTORY_NAME}" -type f -name swiftlint -perm +111 -print -quit)" \
        lint --strict --reporter github-actions-logging
    - name: Resolve package dependencies
      run: xcodebuild -resolvePackageDependencies
    - name: Build
      run: xcodebuild build-for-testing -scheme "CombineUI" -destination "name=$SIMULATOR,OS=latest"
    - name: Test
      run: xcodebuild test-without-building -scheme "CombineUI" -destination "name=$SIMULATOR,OS=latest"
